# Training Notebook

In [96]:
import glob
import os
import numpy as np

# Vision
import cv2

## Utility
import xml.etree.ElementTree as ET
from tqdm import tqdm

import inference_utils

## Displaying in-cell
from IPython.display import Image
import matplotlib.pyplot as plt

%load_ext lab_black

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [2]:
class FishCounter(object):
    import cv2

    def __init__(self, model_config, model_weights):
        self.net = cv2.dnn.readNetFromDarknet(model_config, model_weights)
        self.input_width = 416
        self.input_height = 416

    def inference(self, frame):
        """Run inference on single frame."""
        # Create a 4D blob from a frame.
        blob = cv2.dnn.blobFromImage(
            frame,
            1 / 255,
            (self.input_width, self.input_height),
            [0, 0, 0],
            1,
            crop=False,
        )

        # Sets the input to the network
        self.net.setInput(blob)

        # Runs the forward pass to get output of the output layers
        outs = self.net.forward(self._get_outputs_names(net=self.net))

    def _get_outputs_names(net):
        """Get the names of the output layers."""
        # Get the names of all the layers in the network
        layersNames = net.getLayerNames()
        # Get the names of the output layers, i.e. the layers with unconnected outputs
        return [layersNames[i - 1] for i in net.getUnconnectedOutLayers()]

    def get_annotated_frame(self):
        """Returns main frame with fish highlighted."""
        frame = self.frame.copy()

In [111]:
def get_dimensions_of_annotations(fpath):
    """Extracts dimensions of annotation boxes from xml file for image."""

    class_label = "herring"  # TODO: Will need to accomodate multiple classes

    tree = ET.parse(fpath)
    root = tree.getroot()

    xmins = []
    ymins = []
    xmaxs = []
    ymaxs = []
    for o in root.iter("object"):
        if o.find("name").text == class_label:
            xmins.append(eval(o[4][0].text))
            ymins.append(eval(o[4][1].text))
            xmaxs.append(eval(o[4][2].text))
            ymaxs.append(eval(o[4][3].text))
    return xmins, ymins, xmaxs, ymaxs


def bb_intersection_over_union(boxA, boxB):
    """Compute the intersection over union by taking the intersection area and dividing
    it by the sum of prediction + ground-truth areas - the interesection area"""
    # determine the (x, y)-coordinates of the intersection rectangle
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])
    # compute the area of intersection rectangle
    interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
    print(interArea)
    # compute the area of both the prediction and ground-truth
    # rectangles
    boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
    print(boxAArea)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
    print(boxBArea)

    return interArea / float(boxAArea + boxBArea - interArea)


def find_matching_path(annotations, images):
    """Finds the corresponding image or annotation path (i.e. given on path searches for the corresponding path)"""
    if type(annotations) == str:
        anchor, search = annotations, images
    elif type(images) == str:
        anchor, search = images, annotations
    else:
        print("Somethings wrong")
    return [p for p in search if anchor.split("/")[-1].split(".")[0] in p][
        0
    ]  # only need one

#### Set paths

In [102]:
DOWNLOAD_DIR = os.path.join("/Users", "apowell", "Downloads")
assert os.path.isdir(DOWNLOAD_DIR)

DATA_DIR = os.path.join("..", "data", "Herring")

TRAINING_DIR = os.path.join(DATA_DIR, "Training", "IRWA 2017 (Large+annotations)")
TESTING_DIR = os.path.join(DATA_DIR, "Testing")

os.path.isdir(DATA_DIR)  # assertion that we are pointed to correct folder
WEIGHTS_DIR = os.path.join("..", "weights_and_config")
HERRING_WEIGHTS = os.path.join(WEIGHTS_DIR, "Herring")


folder = "Batch 1"
# Load images and annotations
# images_path1 = os.path.join(TRAINING_DIR, folder, "*.JPG")
# images_path2 = os.path.join(TRAINING_DIR, folder, "*.jpg")
images_path1 = os.path.join(DOWNLOAD_DIR, "HerringTestSet", "Images", "*.jpg")
images = glob.glob(images_path1)  # + glob.glob(images_path2)

# annotation_path = os.path.join(TRAINING_DIR, f"{folder} Annotations", "*.xml")
annotation_path = os.path.join(DOWNLOAD_DIR, "HerringTestSet", "Xml", "*.xml")
annotations = glob.glob(annotation_path)
print("{} images. Annotations: {}".format(len(images), len(annotations)))

94 images. Annotations: 94


In [113]:
# Example: Finding matching paths
test = images[0]
print("test:", test)
test_match = find_matching_path(images=test, annotations=annotations)
print("test match:", test_match)



test /Users/apowell/Downloads/HerringTestSet/Images/1_2016-04-21_21-50-1808716.jpg
test match: /Users/apowell/Downloads/HerringTestSet/Xml/1_2016-04-21_21-50-1808716.xml


## Scoring annotations against inference
**Requirements:** 2 folders: 1 with annotations (e.g. XML), 1 with images
* **Steps:**
  * 1) Run loop on images extracting predicted boxes from each image
  * 2) Scan filenames until box is properly extracted
  * 3) **Scoring Method:**
    * For each annotation find closest/any overlapping boxes (scoring the greater of number of either the annotated or predicted set distinctly)
    * Return average IOU for image
    * Return total number of correctly detected fish

In [67]:
def display_image_comparison(img_path=None, annotated_box=None, predicted_box=None):
    import matplotlib.pyplot as plt
    import cv2

    """Display an image with optional annotated class and predicted class within notebook for comparison.
    image_path: image path to location in memory
    annotated_box: corners in format xmin,xmax,ymin,ymax
    """

    label = "herring"

    img_name = img_path.split("/")[-1].split(".")[0]
    frame = cv2.imread(img_path)

    # Annotated
    cv2.rectangle(
        frame,
        (annotated_box[0], annotated_box[1]),
        (annotated_box[2], annotated_box[3]),
        (178, 255, 255),
        2,
    )

    # Annotated
    # Predicted
    if predicted_box is not None:
        cv2.rectangle(
            frame,
            (predicted_box[0], predicted_box[1]),
            (predicted_box[2], predicted_box[3]),
            (144, 238, 144),
            3,
        )
    cv2.putText(
        frame,
        "Annotated " + label,
        (annotated_box[0], annotated_box[1]),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (178, 255, 255),
        1,
    )
    cv2.putText(
        frame,
        "Predicted " + label,
        (annotated_box[1], annotated_box[2]),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (144, 238, 144),
        1,
    )
    plt.imshow(frame)
    plt.title(img_name)
    plt.show()


## Example files
# 1 count: ../data/Herring/Training/IRWA 2017 (Large+annotations)/Batch 1/2_2017-04-14_11-42-13_large.jpg
# herring_image = "../data/Herring/Training/IRWA 2017 (Large+annotations)/Batch 1/2_2017-04-14_11-42-13_large.jpg"
# boxes = [[56, 134, 97, 48]]

# 1 count: ../data/Herring/Training/IRWA 2017 (Large+annotations)/Batch 1/2_2017-04-14_10-51-06_large.jpg
herring_image = "../data/Herring/Training/IRWA 2017 (Large+annotations)/Batch 1/2_2017-04-14_10-51-06_large.jpg"
boxes = [[6, 110, 107, 56]]

print(herring_image, boxes)
# Get index of annotation path files that contains the path to annotated file matching the non-annoated file
idx = [
    i
    for i in range(len(annotations))
    if herring_image.split("/")[-1].split(".")[0] in annotations[i]
][
    0
]  # Get the first element (multiple matches do not matter)


xmins, xmaxs, ymins, ymaxs = get_dimensions_of_annotations(fpath=annotations[idx])

# Predicted
left, top, width, height = boxes[0][0], boxes[0][1], boxes[0][2], boxes[0][3]
xmin, ymin, xmax, ymax = left, top, left + width, top + height
predicted_box = xmin, ymin, xmax, ymax
# Annotated
annotated_box = xmins[0], xmaxs[0], ymins[0], ymaxs[0]
print("IOU Score:", bb_intersection_over_union(boxA=predicted_box, boxB=annotated_box))

display_image_comparison(
    img_path=herring_image, annotated_box=annotated_box, predicted_box=predicted_box
)  # predicted_box

../data/Herring/Training/IRWA 2017 (Large+annotations)/Batch 1/2_2017-04-14_10-51-06_large.jpg [[6, 110, 107, 56]]


IndexError: list index out of range

## Evaluation

In [103]:
## Initialize the parameters
# Confidence threshold
conf_threshold = 0.5
# Non-maximum suppression threshold (maximum bounding box)
nms_threshold = 0.05
input_width = 416  # Width of network's input image
input_height = 416  # Height of network's input image

# Load class name
classes = "Herring"
# Give the configuration and weight files for the model and load the network using them.
modelConfiguration = os.path.join(HERRING_WEIGHTS, "herring.cfg")
modelWeights = os.path.join(HERRING_WEIGHTS, "herring_final.weights")
net = cv2.dnn.readNetFromDarknet(modelConfiguration, modelWeights)


iou_scores = []
annotated_counts = []
predicted_counts = []
# Loop through annotated files
for a in tqdm(annotations):
    name = a.split("/")[-1].split(".")[0]

    # Loop through image files (non-annotated) to make a prediction on
    for herring_image in images:

        if name not in herring_image:
            continue

        frame = cv2.imread(herring_image)

        # # Get frame from the video
        # hasFrame, frame = cap.read()

        input_width, input_height, _ = frame.shape
        input_width = input_height = min(input_width, input_height)
        input_width = 416  # Width of network's input image
        input_height = 416  # Height of network's input image

        print(input_height, input_width)
        # Create a 4D blob from a frame.
        blob = cv2.dnn.blobFromImage(
            frame, 1 / 255, (input_width, input_height), [0, 0, 0], 1, crop=False
        )

        # Sets the input to the network
        net.setInput(blob)

        # Runs the forward pass to get output of the output layers
        outs = net.forward(inference_utils.get_outputs_names(net=net))
        # break
        # Remove the bounding boxes with low confidence
        counts, boxes = inference_utils.postprocess(
            frame=frame,
            outs=outs,
            tracker=None,
            conf_threshold=conf_threshold,
            nms_threshold=nms_threshold,
            classes=classes,
        )

        print(boxes)
        # cv2.imshow(herring_image, frame)
        # cv2.waitKey(0)
        print("Counts:", counts)

        # Get score
        xmins, xmaxs, ymins, ymaxs = get_dimensions_of_annotations(fpath=a)
        # Predicted
        if len(boxes) == 0:  # If nothing was predicted
            boxes = [[0, 0, 0, 0]]
        left, top, width, height = boxes[0][0], boxes[0][1], boxes[0][2], boxes[0][3]
        xmin, ymin, xmax, ymax = left, top, left + width, top + height
        predicted_box = xmin, ymin, xmax, ymax
        # Annotated
        if len(xmins) == 0:  # If nothing was annotated
            annotated_box = [0, 0, 0, 0]
            annotated_count = 0
        else:
            annotated_box = xmins[0], xmaxs[0], ymins[0], ymaxs[0]
            annotated_count = len(xmins)

        annotated_counts.append(annotated_count)
        predicted_counts.append(counts)
        iou_score = bb_intersection_over_union(boxA=predicted_box, boxB=annotated_box)
        iou_scores.append(iou_score)
        print("IOU Score:", iou_score)

        print()
    cv2.destroyAllWindows()

  0%|          | 0/94 [00:00<?, ?it/s]

416 416


  2%|▏         | 2/94 [00:00<00:23,  3.98it/s]

[0.37076646 0.62617767 0.5142306  0.30055088 0.94516844 0.94516844]
BOXES [[72, 228, 329, 144]] [0] [0]
counts 1
[[72, 228, 329, 144]]
Counts: 1
45175
47850
45731
IOU Score: 0.9332520761889022

416 416
[0.7232271  0.66355705 0.543609   0.26670778 0.909749   0.909749  ]
BOXES [[288, 254, 347, 128]] [0] [0]
counts 1
[[288, 254, 347, 128]]
Counts: 1
36176
44892
36624
IOU Score: 0.7978826643140715

416 416


  3%|▎         | 3/94 [00:00<00:23,  3.90it/s]

[0.34684214 0.6207243  0.52821535 0.23552504 0.94160265 0.94160265]
BOXES [[52, 240, 338, 113]] [0] [0]
counts 1
[[52, 240, 338, 113]]
Counts: 1
35226
38646
41406
IOU Score: 0.7858385758265293

416 416


  5%|▌         | 5/94 [00:01<00:19,  4.66it/s]

[0.27137616 0.5909968  0.53890646 0.32005793 0.9478845  0.9478845 ]
[0.94730365 0.58369726 0.09907495 0.14638363 0.84516746 0.84516746]
BOXES [[1, 206, 344, 153], [574, 245, 63, 70]] [0 1] [0, 0]
counts 2
[[1, 206, 344, 153], [574, 245, 63, 70]]
Counts: 2
49742
53130
66538
IOU Score: 0.71135200068644

416 416
[0.43998474 0.6321185  0.5415118  0.26919815 0.9418064  0.9418064 ]
BOXES [[108, 238, 346, 129]] [0] [0]
counts 1
[[108, 238, 346, 129]]
Counts: 1
44763
45110
48330
IOU Score: 0.9195924153090782

416 416


  6%|▋         | 6/94 [00:01<00:17,  4.91it/s]

[0.37075773 0.6354888  0.4071458  0.20766798 0.92699665 0.92699665]
[0.94930714 0.6351875  0.09969059 0.13809986 0.879902   0.879902  ]
BOXES [[107, 255, 260, 99], [575, 271, 63, 66]] [0 1] [0, 0]
counts 2
[[107, 255, 260, 99], [575, 271, 63, 66]]
Counts: 2
22022
26100
22022
IOU Score: 0.8437547892720306

416 416


  7%|▋         | 7/94 [00:01<00:18,  4.72it/s]

[0.31993294 0.5901342  0.4550493  0.20341226 0.9329713  0.9329713 ]
BOXES [[58, 234, 291, 97]] [0] [0]
counts 1
[[58, 234, 291, 97]]
Counts: 1
28616
28616
32704
IOU Score: 0.875

416 416


  9%|▊         | 8/94 [00:01<00:20,  4.19it/s]

[0.34620613 0.5691718  0.46827376 0.22240259 0.9051191  0.9051191 ]
BOXES [[71, 220, 299, 106]] [0] [0]
counts 1
[[71, 220, 299, 106]]
Counts: 1
9438
32100
18368
IOU Score: 0.23002680965147454

416 416


 11%|█         | 10/94 [00:02<00:18,  4.45it/s]

[0.45442435 0.60320145 0.5740494  0.24252747 0.9493154  0.9493154 ]
BOXES [[106, 231, 367, 116]] [0] [0]
counts 1
[[106, 231, 367, 116]]
Counts: 1
40595
43056
42245
IOU Score: 0.908043663042992

416 416
[0.6897242  0.52805346 0.37667164 0.20483825 0.9297597  0.9297597 ]
BOXES [[320, 204, 241, 98]] [0] [0]
counts 1
[[320, 204, 241, 98]]
Counts: 1
23364
23958
26973
IOU Score: 0.8475350963108064

416 416


 12%|█▏        | 11/94 [00:02<00:19,  4.29it/s]

[0.3208179  0.6040403  0.45677498 0.161495   0.93710333 0.93710333]
BOXES [[59, 250, 292, 77]] [0] [0]
counts 1
[[59, 250, 292, 77]]
Counts: 1
18130
22854
18130
IOU Score: 0.7932965782795134

416 416


 13%|█▎        | 12/94 [00:02<00:19,  4.22it/s]

[0.7505356  0.5852606  0.3615247  0.17228056 0.9240052  0.9240052 ]
BOXES [[364, 239, 231, 82]] [0] [0]
counts 1
[[364, 239, 231, 82]]
Counts: 1
15042
19256
15180
IOU Score: 0.7756007012478086

416 416


 15%|█▍        | 14/94 [00:03<00:17,  4.58it/s]

[0.56312454 0.5749503  0.35202038 0.17354204 0.9272542  0.9272542 ]
BOXES [[247, 233, 225, 83]] [0] [0]
counts 1
[[247, 233, 225, 83]]
Counts: 1
18592
18984
20340
IOU Score: 0.8967779278410187

416 416
[0.62486374 0.5738801  0.70655984 0.37095487 0.9439708  0.9439708 ]
BOXES [[173, 186, 452, 178]] [0] [0]
counts 1
[[173, 186, 452, 178]]
Counts: 1
80371
81087
86714
IOU Score: 0.9192611231842617

416 416


 17%|█▋        | 16/94 [00:03<00:15,  5.05it/s]

[0.47457287 0.61953735 0.41954234 0.20583874 0.9489468  0.9489468 ]
BOXES [[169, 248, 268, 98]] [0] [0]
counts 1
[[169, 248, 268, 98]]
Counts: 1
21845
26631
21845
IOU Score: 0.8202846306935526

416 416
[0.47011334 0.6543294  0.470619   0.23560725 0.93396306 0.93396306]
BOXES [[149, 257, 301, 113]] [0] [0]
counts 1
[[149, 257, 301, 113]]
Counts: 1
32616
34428
33372
IOU Score: 0.927012278308322

416 416


 19%|█▉        | 18/94 [00:03<00:14,  5.40it/s]

[0.6483742  0.58370715 0.33463416 0.14803419 0.92491275 0.92491275]
BOXES [[307, 244, 214, 71]] [0] [0]
counts 1
[[307, 244, 214, 71]]
Counts: 1
14910
15480
16247
IOU Score: 0.8866028423618957

416 416
[0.1986342  0.6131262  0.38478497 0.1717144  0.93829155 0.93829155]
BOXES [[4, 253, 246, 82]] [0] [0]
counts 1
[[4, 253, 246, 82]]
Counts: 1
16614
20501
17466
IOU Score: 0.7780639722755585

416 416


 20%|██        | 19/94 [00:04<00:15,  4.96it/s]

[0.21345234 0.6531277  0.4209289  0.23517647 0.9336457  0.9336457 ]
BOXES [[1, 257, 269, 112]] [0] [0]
counts 1
[[1, 257, 269, 112]]
Counts: 1
28248
30510
28248
IOU Score: 0.9258603736479842

416 416
[0.28926888 0.6342215  0.51817936 0.25717127 0.940283   0.940283  ]


 21%|██▏       | 20/94 [00:04<00:15,  4.93it/s]

BOXES [[19, 242, 331, 123]] [0] [0]
counts 1
[[19, 242, 331, 123]]
Counts: 1
36424
41168
37206
IOU Score: 0.8682717520858164

416 416


 23%|██▎       | 22/94 [00:04<00:14,  4.91it/s]

[0.6799153  0.5627844  0.55184937 0.23326632 0.937973   0.937973  ]
BOXES [[258, 214, 353, 111]] [0] [0]
counts 1
[[258, 214, 353, 111]]
Counts: 1
34884
39648
36252
IOU Score: 0.8504973668812171

416 416
[0.2732934  0.6534552  0.52976173 0.25288346 0.9443923  0.9443923 ]
BOXES [[4, 252, 339, 121]] [0] [0]
counts 1
[[4, 252, 339, 121]]
Counts: 1
36624
41480
36624
IOU Score: 0.8829315332690453

416 416


 24%|██▍       | 23/94 [00:05<00:14,  4.82it/s]

[0.30013755 0.57062274 0.549683   0.37287745 0.9512945  0.9512945 ]
BOXES [[16, 184, 351, 178]] [0] [0]
counts 1
[[16, 184, 351, 178]]
Counts: 1
58587
63008
59249
IOU Score: 0.9201664834301869

416 416


 26%|██▌       | 24/94 [00:05<00:14,  4.71it/s]

[0.79184854 0.60291314 0.37220493 0.18013594 0.9217418  0.9217418 ]
BOXES [[387, 246, 238, 86]] [0] [0]
counts 1
[[387, 246, 238, 86]]
Counts: 1
15232
20793
15776
IOU Score: 0.7138773023386605

416 416


 27%|██▋       | 25/94 [00:05<00:15,  4.56it/s]

[0.6847864  0.5854094  0.34342682 0.16033244 0.93251777 0.93251777]
BOXES [[328, 242, 219, 76]] [0] [0]
counts 1
[[328, 242, 219, 76]]
Counts: 1
16500
16940
18942
IOU Score: 0.8513053348467651

416 416


 28%|██▊       | 26/94 [00:05<00:14,  4.64it/s]

[0.8010291  0.54967177 0.321942   0.17761275 0.92484933 0.92484933]
BOXES [[409, 220, 206, 85]] [0] [0]
counts 1
[[409, 220, 206, 85]]
Counts: 1
16564
17802
17347
IOU Score: 0.8912563895614743

416 416


 29%|██▊       | 27/94 [00:05<00:15,  4.46it/s]

[0.21984233 0.57838327 0.41981295 0.21590304 0.9295352  0.9295352 ]
BOXES [[6, 225, 268, 103]] [0] [0]
counts 1
[[6, 225, 268, 103]]
Counts: 1
26058
27976
29754
IOU Score: 0.8227456428391008

416 416
[0.590087   0.62952125 0.54212695 0.25842008 0.9422074  0.9422074 ]
BOXES [[204, 240, 346, 124]] [0] [0]
counts 1
[[204, 240, 346, 124]]
Counts: 1
36852
43375
36852
IOU Score: 0.8496138328530259



 31%|███       | 29/94 [00:06<00:13,  4.68it/s]

416 416
[0.36806914 0.62660795 0.66028076 0.2826855  0.9475822  0.9475822 ]
BOXES [[24, 232, 422, 135]] [0] [0]
counts 1
[[24, 232, 422, 135]]
Counts: 1
49875
57528
50250
IOU Score: 0.8613543339723331

416 416


 33%|███▎      | 31/94 [00:06<00:13,  4.68it/s]

[0.5664516  0.5256728  0.6002198  0.22820106 0.93550104 0.93550104]
BOXES [[170, 197, 384, 109]] [0] [0]
counts 1
[[170, 197, 384, 109]]
Counts: 1
40920
42350
43524
IOU Score: 0.9102638252435823

416 416
[0.7949606  0.6241384  0.4001742  0.19412166 0.9211984  0.9211984 ]
BOXES [[380, 252, 256, 93]] [0] [0]
counts 1
[[380, 252, 256, 93]]
Counts: 1
23130
24158
30303
IOU Score: 0.7382464651622993

416 416


 34%|███▍      | 32/94 [00:07<00:14,  4.40it/s]

[0.73196465 0.5750352  0.42240766 0.1793914  0.93069685 0.93069685]
BOXES [[333, 233, 270, 86]] [0] [0]
counts 1
[[333, 233, 270, 86]]
Counts: 1
23577
23577
26880
IOU Score: 0.8771205357142857

416 416


 35%|███▌      | 33/94 [00:07<00:14,  4.34it/s]

[0.6580374  0.63697207 0.5634058  0.26454324 0.93932617 0.93932617]
BOXES [[241, 242, 360, 126]] [0] [0]
counts 1
[[241, 242, 360, 126]]
Counts: 1
45085
45847
47925
IOU Score: 0.9260172119867727

416 416


 36%|███▌      | 34/94 [00:07<00:14,  4.22it/s]

[0.4111867  0.62121046 0.557511   0.24239562 0.9525484  0.9525484 ]
BOXES [[85, 240, 356, 116]] [0] [0]
counts 1
[[85, 240, 356, 116]]
Counts: 1
36435
41769
36435
IOU Score: 0.8722976370035194

416 416


 37%|███▋      | 35/94 [00:07<00:13,  4.22it/s]

[0.46677047 0.524994   0.42227727 0.18000625 0.9304019  0.9304019 ]
BOXES [[163, 208, 270, 86]] [0] [0]
counts 1
[[163, 208, 270, 86]]
Counts: 1
19789
23577
21845
IOU Score: 0.7720126399563063

416 416


 38%|███▊      | 36/94 [00:08<00:14,  4.02it/s]

[0.7064811  0.5963663  0.38099247 0.15591134 0.92605203 0.92605203]
BOXES [[330, 249, 243, 74]] [0] [0]
counts 1
[[330, 249, 243, 74]]
Counts: 1
16038
18300
16368
IOU Score: 0.8608695652173913

416 416


 40%|████      | 38/94 [00:08<00:13,  4.24it/s]

[0.23359193 0.59702516 0.4043026  0.17619053 0.9337614  0.9337614 ]
BOXES [[20, 244, 258, 84]] [0] [0]
counts 1
[[20, 244, 258, 84]]
Counts: 1
18012
22015
20746
IOU Score: 0.7277869812921735

416 416
[0.59077865 0.581333   0.59271866 0.22509351 0.89240843 0.89240843]
[0.8243447  0.55408895 0.33466545 0.16688858 0.8162273  0.8162273 ]
BOXES [[188, 225, 379, 108], [420, 225, 214, 80]] [0] [0, 0]
counts 2
[[188, 225, 379, 108], [420, 225, 214, 80]]
Counts: 2
30738
41420
34404
IOU Score: 0.6817637404072218

416 416


 43%|████▎     | 40/94 [00:08<00:11,  4.87it/s]

[0.23474762 0.53066146 0.4558665  0.2230369  0.9401002  0.9401002 ]
BOXES [[4, 200, 291, 107]] [0] [0]
counts 1
[[4, 200, 291, 107]]
Counts: 1
30923
31536
32704
IOU Score: 0.9281447909475643

416 416
[0.49923995 0.56020635 0.3365497  0.18829097 0.93194824 0.93194824]
BOXES [[211, 223, 215, 90]] [0] [0]
counts 1
[[211, 223, 215, 90]]
Counts: 1
19565
19656
22321
IOU Score: 0.872969837587007

416 416


 45%|████▍     | 42/94 [00:09<00:09,  5.26it/s]

[0.56779516 0.58740366 0.37252977 0.15607335 0.9276992  0.9276992 ]
BOXES [[244, 244, 238, 74]] [0] [0]
counts 1
[[244, 244, 238, 74]]
Counts: 1
16969
17925
17750
IOU Score: 0.9071420934459532

416 416
[0.67231655 0.5502401  0.41960466 0.20342156 0.9272149  0.9272149 ]
BOXES [[296, 215, 268, 97]] [0] [0]
counts 1
[[296, 215, 268, 97]]
Counts: 1
25175
26362
26334
IOU Score: 0.9147560045056502

416 416


 47%|████▋     | 44/94 [00:09<00:09,  5.28it/s]

[0.29144493 0.59663683 0.39517057 0.18651891 0.92129356 0.92129356]
BOXES [[60, 241, 252, 89]] [0] [0]
counts 1
[[60, 241, 252, 89]]
Counts: 1
22140
22770
25250
IOU Score: 0.8554868624420402

416 416
[0.23997614 0.5961249  0.33499038 0.1516014  0.92583656 0.92583656]
BOXES [[46, 250, 214, 72]] [0] [0]
counts 1
[[46, 250, 214, 72]]
Counts: 1
15111
15695
16767
IOU Score: 0.8709008126332776

416 416


 48%|████▊     | 45/94 [00:09<00:09,  5.23it/s]

[0.702096   0.52901834 0.44542426 0.19614035 0.9376944  0.9376944 ]
BOXES [[306, 206, 285, 94]] [0] [0]
counts 1
[[306, 206, 285, 94]]
Counts: 1
22041
27170
22515
IOU Score: 0.7973158732455505

416 416


 50%|█████     | 47/94 [00:10<00:08,  5.24it/s]

[0.68028206 0.493241   0.40055183 0.19261375 0.92277867 0.92277867]
[0.37795052 0.57037205 0.29709283 0.13803741 0.8929228  0.8929228 ]
BOXES [[307, 190, 256, 92], [146, 240, 190, 66]] [0 1] [0, 0]
counts 2
[[307, 190, 256, 92], [146, 240, 190, 66]]
Counts: 2
20916
23901
20916
IOU Score: 0.8751098280406677

416 416
[0.7931262  0.6384168  0.38088673 0.17805122 0.9279007  0.9279007 ]
BOXES [[385, 263, 243, 85]] [0] [0]
counts 1
[[385, 263, 243, 85]]
Counts: 1
14616
20984
14805
IOU Score: 0.6903131346526237

416 416


 52%|█████▏    | 49/94 [00:10<00:08,  5.35it/s]

[0.7600241  0.53373814 0.3586264  0.221835   0.93950933 0.93950933]
BOXES [[371, 203, 229, 106]] [0] [0]
counts 1
[[371, 203, 229, 106]]
Counts: 1
21600
24610
23760
IOU Score: 0.8068733657078819

416 416
[0.26847178 0.6874332  0.54359657 0.22503601 0.9531179  0.9531179 ]
BOXES [[-2, 275, 347, 108]] [0] [0]
counts 1
[[-2, 275, 347, 108]]
Counts: 1
32825
37932
32825
IOU Score: 0.8653643361805335

416 416


 53%|█████▎    | 50/94 [00:10<00:09,  4.69it/s]

[0.380468   0.5880166  0.44501048 0.18313739 0.93188864 0.93188864]
BOXES [[101, 238, 284, 87]] [0] [0]
counts 1
[[101, 238, 284, 87]]
Counts: 1
23320
25080
28462
IOU Score: 0.7716233207597115

416 416


 54%|█████▍    | 51/94 [00:11<00:09,  4.47it/s]

[0.6443764  0.58846897 0.5970696  0.2441917  0.93383086 0.93383086]
BOXES [[221, 223, 382, 117]] [0] [0]
counts 1
[[221, 223, 382, 117]]
Counts: 1
43542
45194
53136
IOU Score: 0.7947360735927576

416 416


 55%|█████▌    | 52/94 [00:11<00:09,  4.50it/s]

[0.34632558 0.58810437 0.6551551  0.26600873 0.9380579  0.9380579 ]
BOXES [[11, 218, 419, 127]] [0] [0]
counts 1
[[11, 218, 419, 127]]
Counts: 1
50840
53760
55208
IOU Score: 0.8746215249105422

416 416
[0.46632499 0.60044837 0.35371917 0.15932938 0.9366841  0.9366841 ]
BOXES [[185, 250, 226, 76]] [0] [0]
counts 1
[[185, 250, 226, 76]]
Counts: 1


 56%|█████▋    | 53/94 [00:11<00:08,  4.62it/s]

16798
17479
17094
IOU Score: 0.9450351617440225

416 416


 59%|█████▊    | 55/94 [00:11<00:08,  4.58it/s]

[0.8653936  0.66103053 0.25319535 0.15562138 0.921055   0.921055  ]
BOXES [[472, 280, 162, 74]] [0] [0]
counts 1
[[472, 280, 162, 74]]
Counts: 1
9780
12225
11040
IOU Score: 0.7252502780867631

416 416
[0.7135397  0.54067326 0.33324447 0.18323508 0.9337469  0.9337469 ]
BOXES [[349, 215, 213, 87]] [0] [0]
counts 1
[[349, 215, 213, 87]]
Counts: 1
17098
18832
17510
IOU Score: 0.8884847225109125

416 416


 60%|█████▉    | 56/94 [00:12<00:08,  4.71it/s]

[0.8081296  0.62714374 0.31372583 0.15980783 0.91612995 0.91612995]
BOXES [[417, 263, 200, 76]] [0] [0]
counts 1
[[417, 263, 200, 76]]
Counts: 1
10545
15477
10545
IOU Score: 0.681333591781353

416 416


 62%|██████▏   | 58/94 [00:12<00:07,  4.60it/s]

[0.75045294 0.5788157  0.36626384 0.17183684 0.9305894  0.9305894 ]
BOXES [[363, 236, 234, 82]] [0] [0]
counts 1
[[363, 236, 234, 82]]
Counts: 1
17550
19505
17550
IOU Score: 0.8997692899256601

416 416
[0.5874779  0.5356747  0.38238752 0.21165632 0.9359308  0.9359308 ]
BOXES [[253, 206, 244, 101]] [0] [0]
counts 1
[[253, 206, 244, 101]]
Counts: 1
24276
24990
26620
IOU Score: 0.8881246798858564

416 416


 64%|██████▍   | 60/94 [00:13<00:07,  4.67it/s]

[0.7233266  0.56981444 0.37841508 0.18277964 0.9311267  0.9311267 ]
BOXES [[341, 229, 242, 87]] [0] [0]
counts 1
[[341, 229, 242, 87]]
Counts: 1
18720
21384
18720
IOU Score: 0.8754208754208754

416 416
[0.58624065 0.5859791  0.75674206 0.1999256  0.9395513  0.9395513 ]
BOXES [[133, 233, 484, 95]] [0] [0]
counts 1
[[133, 233, 484, 95]]
Counts: 1
28612
46560
31722
IOU Score: 0.5760418763841353



 65%|██████▍   | 61/94 [00:13<00:06,  4.83it/s]

416 416
[0.5328629  0.5861331  0.6243048  0.27172554 0.9393435  0.9393435 ]
BOXES [[141, 216, 399, 130]] [0] [0]
counts 1
[[141, 216, 399, 130]]
Counts: 1
47000
52400
47000
IOU Score: 0.8969465648854962

416 416


 67%|██████▋   | 63/94 [00:13<00:06,  5.15it/s]

[0.39746004 0.4803701  0.57477653 0.29098052 0.93230116 0.93230116]
[0.08401346 0.6996457  0.17573482 0.21952254 0.89623827 0.89623827]
BOXES [[70, 160, 367, 139], [-3, 282, 112, 105]] [0 1] [0, 0]
counts 2
[[70, 160, 367, 139], [-3, 282, 112, 105]]
Counts: 2
50260
51520
61178
IOU Score: 0.8049585188506999

416 416
[0.20020615 0.5866732  0.4055236  0.21749021 0.9245262  0.9245262 ]
BOXES [[-1, 229, 259, 104]] [0] [0]
counts 1
[[-1, 229, 259, 104]]
Counts: 1
26460
27300
27216
IOU Score: 0.9431137724550899

416 416


 68%|██████▊   | 64/94 [00:13<00:05,  5.23it/s]

[0.88929456 0.6252875  0.22658697 0.20307302 0.9233189  0.9233189 ]
BOXES [[496, 251, 145, 97]] [0] [0]
counts 1
[[496, 251, 145, 97]]
Counts: 1
12831
14308
12831
IOU Score: 0.8967710371819961

416 416


 70%|███████   | 66/94 [00:14<00:05,  5.25it/s]

[0.17280237 0.5987518  0.33668894 0.21439646 0.92006844 0.92006844]
[0.69669956 0.5455706  0.408411   0.19795774 0.9465786  0.9465786 ]
BOXES [[2, 236, 215, 102], [314, 213, 261, 95]] [1 0] [0, 0]
counts 2
[[2, 236, 215, 102], [314, 213, 261, 95]]
Counts: 2
0
22248
23852
IOU Score: 0.0

416 416
[0.43413228 0.6279523  0.38864693 0.2095236  0.9276431  0.9276431 ]
BOXES [[153, 251, 248, 100]] [0] [0]
counts 1
[[153, 251, 248, 100]]
Counts: 1
25149
25149
28930
IOU Score: 0.8693052194953336

416 416


 72%|███████▏  | 68/94 [00:14<00:05,  5.16it/s]

[0.4129042  0.6348277  0.5752088  0.18880707 0.9094407  0.9094407 ]
BOXES [[80, 259, 368, 90]] [0] [0]
counts 1
[[80, 259, 368, 90]]
Counts: 1
16770
33579
17927
IOU Score: 0.48278443113772457

416 416
[0.47996077 0.5907364  0.43332237 0.1925259  0.93109614 0.93109614]
BOXES [[168, 237, 277, 92]] [0] [0]
counts 1
[[168, 237, 277, 92]]
Counts: 1
23490
25854
25839
IOU Score: 0.8328901180725454



 73%|███████▎  | 69/94 [00:14<00:04,  5.16it/s]

416 416
[0.25028422 0.66223204 0.49096563 0.27387226 0.94107836 0.94107836]
BOXES [[3, 251, 314, 131]] [0] [0]
counts 1
[[3, 251, 314, 131]]
Counts: 1
38682
41580
38934
IOU Score: 0.9246987951807228

416 416


 76%|███████▌  | 71/94 [00:15<00:04,  5.26it/s]

[0.6334802  0.5750334  0.5223548  0.23127642 0.94311625 0.94311625]
BOXES [[238, 220, 334, 111]] [0] [0]
counts 1
[[238, 220, 334, 111]]
Counts: 1
36297
37520
36624
IOU Score: 0.9590456310936137

416 416
[0.4890995  0.62945485 0.61335635 0.27434036 0.9441676  0.9441676 ]
BOXES [[117, 236, 392, 131]] [0] [0]
counts 1
[[117, 236, 392, 131]]
Counts: 1
49632
51876
52640
IOU Score: 0.9043072662342395

416 416


 78%|███████▊  | 73/94 [00:15<00:03,  5.38it/s]

[0.2705773  0.58268106 0.51769584 0.22363609 0.93307173 0.93307173]
BOXES [[7, 225, 331, 107]] [0] [0]
counts 1
[[7, 225, 331, 107]]
Counts: 1
33480
35856
34100
IOU Score: 0.9178638008553569

416 416
[0.6420211  0.6243016  0.6926851  0.35155705 0.941365   0.941365  ]
BOXES [[188, 215, 443, 168]] [0] [0]
counts 1
[[188, 215, 443, 168]]
Counts: 1
75036
75036
113678
IOU Score: 0.6600749485388554

416 416


 80%|███████▉  | 75/94 [00:15<00:03,  5.34it/s]

[0.350238   0.63589734 0.33742803 0.13757409 0.93113446 0.93113446]
[0.7662044  0.6344005  0.32164016 0.14563765 0.92759717 0.92759717]
BOXES [[116, 272, 215, 66], [387, 269, 205, 69]] [0 1] [0, 0]
counts 2
[[116, 272, 215, 66], [387, 269, 205, 69]]
Counts: 2
0
14472
12383
IOU Score: 0.0

416 416
[0.73977345 0.5823792  0.4819454  0.20595759 0.9362615  0.9362615 ]
BOXES [[319, 230, 308, 98]] [0] [0]
counts 1
[[319, 230, 308, 98]]
Counts: 1
30591
30591
35409
IOU Score: 0.863932898415657



 81%|████████  | 76/94 [00:16<00:03,  5.34it/s]

416 416
[0.79899985 0.6034973  0.36595073 0.18217094 0.9252843  0.9252843 ]
BOXES [[394, 245, 234, 87]] [0] [0]
counts 1
[[394, 245, 234, 87]]
Counts: 1
15890
20680
15890
IOU Score: 0.7683752417794971

416 416


 83%|████████▎ | 78/94 [00:16<00:03,  5.23it/s]

[0.26877907 0.6344128  0.40907398 0.18646723 0.9223718  0.9223718 ]
BOXES [[41, 259, 261, 89]] [0] [0]
counts 1
[[41, 259, 261, 89]]
Counts: 1
23310
23580
28930
IOU Score: 0.7982876712328767

416 416
[0.6485107  0.6078847  0.5436648  0.21582963 0.9426934  0.9426934 ]
BOXES [[241, 239, 347, 103]] [0] [0]
counts 1
[[241, 239, 347, 103]]
Counts: 1
30969
36192
30969
IOU Score: 0.8556863395225465



 84%|████████▍ | 79/94 [00:16<00:02,  5.16it/s]

416 416
[0.81868744 0.60877806 0.32660896 0.15827624 0.9333722  0.9333722 ]
[0.54912305 0.6183717  0.30588013 0.1648279  0.95040566 0.95040566]
BOXES [[418, 254, 209, 75], [253, 256, 195, 79]] [1] [0, 0]
counts 2
[[418, 254, 209, 75], [253, 256, 195, 79]]
Counts: 2
15120
15960
15840
IOU Score: 0.9064748201438849

416 416


 86%|████████▌ | 81/94 [00:16<00:02,  5.41it/s]

[0.28401142 0.67893857 0.56582654 0.24194112 0.94066113 0.94066113]
BOXES [[0, 267, 362, 116]] [0] [0]
counts 1
[[0, 267, 362, 116]]
Counts: 1
32010
42471
32010
IOU Score: 0.7536907536907537

416 416
[0.29276797 0.5897313  0.36321416 0.16725633 0.9301481  0.9301481 ]
BOXES [[71, 243, 232, 80]] [0] [0]
counts 1
[[71, 243, 232, 80]]
Counts: 1
16720
18873
16720
IOU Score: 0.8859216870661792

416 416


 88%|████████▊ | 83/94 [00:17<00:02,  5.36it/s]

[0.30239126 0.5946647  0.53028435 0.21225542 0.91980684 0.91980684]
BOXES [[23, 234, 339, 101]] [0] [0]
counts 1
[[23, 234, 339, 101]]
Counts: 1
32334
34680
35616
IOU Score: 0.8517464833254307

416 416
[0.27858412 0.6126193  0.55370253 0.28096235 0.942017   0.942017  ]
BOXES [[1, 227, 354, 134]] [0] [0]
counts 1
[[1, 227, 354, 134]]
Counts: 1
44730
47925
47784
IOU Score: 0.877420114164656

416 416


 90%|█████████ | 85/94 [00:17<00:01,  5.18it/s]

[0.78272736 0.6140332  0.35708827 0.18071848 0.9309507  0.9309507 ]
BOXES [[386, 251, 228, 86]] [0] [0]
counts 1
[[386, 251, 228, 86]]
Counts: 1
14003
19923
14003
IOU Score: 0.7028559955829945

416 416
[0.5746339  0.6051444  0.35745233 0.15774396 0.9346548  0.9346548 ]
BOXES [[253, 252, 228, 75]] [0] [0]
counts 1
[[253, 252, 228, 75]]
Counts: 1
15620
17404
16060
IOU Score: 0.8753642681013226

416 416


 93%|█████████▎| 87/94 [00:18<00:01,  5.24it/s]

[0.65991455 0.60257155 0.55486643 0.22929488 0.9420563  0.9420563 ]
BOXES [[244, 234, 355, 110]] [0] [0]
counts 1
[[244, 234, 355, 110]]
Counts: 1
34900
39516
34900
IOU Score: 0.8831865573438608

416 416
[0.70249176 0.49548358 0.35831323 0.20803823 0.9192009  0.9192009 ]
[0.39142224 0.54435766 0.34209067 0.19128653 0.9017634  0.9017634 ]
BOXES [[334, 187, 229, 99], [141, 215, 218, 91]] [0 1] [0, 0]
counts 2
[[334, 187, 229, 99], [141, 215, 218, 91]]
Counts: 2
23000
23000
30736
IOU Score: 0.7483081728266527

416 416


 95%|█████████▍| 89/94 [00:18<00:00,  5.40it/s]

[0.7459537  0.6171144  0.34547046 0.16354674 0.9334494  0.9334494 ]
BOXES [[366, 257, 221, 78]] [0] [0]
counts 1
[[366, 257, 221, 78]]
Counts: 1
14839
17538
14910
IOU Score: 0.8426940768924982

416 416
[0.7514604  0.5432896  0.4847816  0.20181921 0.9424414  0.9424414 ]
[0.11002939 0.70764023 0.20260578 0.24101654 0.8938631  0.8938631 ]
BOXES [[325, 212, 310, 96], [5, 281, 129, 115]] [0 1] [0, 0]
counts 2
[[325, 212, 310, 96], [5, 281, 129, 115]]
Counts: 2
0
30167
14630
IOU Score: 0.0

416 416


 97%|█████████▋| 91/94 [00:18<00:00,  5.56it/s]

[0.6635752  0.70139575 0.5403904  0.24297749 0.9289744  0.9289744 ]
BOXES [[251, 278, 345, 116]] [0] [0]
counts 1
[[251, 278, 345, 116]]
Counts: 1
36270
40482
38750
IOU Score: 0.8442344397374424

416 416
[0.48869583 0.58961284 0.4343481  0.2481359  0.92749214 0.92749214]
[0.10642012 0.6383523  0.20666902 0.2030523  0.9095578  0.9095578 ]
BOXES [[173, 223, 277, 119], [2, 257, 132, 97]] [0 1] [0, 0]
counts 2
[[173, 223, 277, 119], [2, 257, 132, 97]]
Counts: 2
31860
33360
33210
IOU Score: 0.9178910976663786

416 416


 99%|█████████▉| 93/94 [00:19<00:00,  5.63it/s]

[0.9112899  0.50406724 0.16773257 0.15382396 0.88390905 0.88390905]
BOXES [[529, 204, 107, 73]] [0] [0]
counts 1
[[529, 204, 107, 73]]
Counts: 1
6732
7992
7004
IOU Score: 0.8146176185866408

416 416
[0.32009712 0.59073603 0.39301378 0.16648228 0.9256019  0.9256019 ]
BOXES [[78, 243, 251, 79]] [0] [0]
counts 1
[[78, 243, 251, 79]]
Counts: 1
19600
20160
21070
IOU Score: 0.9061488673139159

416 416


100%|██████████| 94/94 [00:19<00:00,  4.84it/s]

[0.3289839  0.71345925 0.522956   0.280719   0.9146465  0.9146465 ]
BOXES [[43, 275, 334, 134]] [0] [0]
counts 1
[[43, 275, 334, 134]]
Counts: 1
36624
45225
36624
IOU Score: 0.8098175787728027



In [104]:
print("average IOU:", np.mean(iou_scores))
print("Total annotated counts:", sum(annotated_counts))
print("Total predicted counts:", sum(predicted_counts))
print(
    f"Ratio of predicted to expected: { sum(predicted_counts) / sum(annotated_counts):.3f}"
)

average IOU: 0.805932661840877
Total annotated counts: 112
Total predicted counts: 105
Ratio of predicted to expected: 0.938
